DROP TABLE IF EXISTS `homunculus_db2`;
CREATE TABLE `homunculus_db2` (
	`Class` smallint(6) unsigned NOT NULL default '0',
	`EvoClass` smallint(6) unsigned NOT NULL default '0',
	`Name` varchar(24) NOT NULL default '',
	`FoodID` smallint(6) unsigned NOT NULL default '0',
	`FoodDelay` int(11) unsigned NOT NULL default '0',
	`BaseSize` tinyint(2) unsigned NOT NULL default '0',
	`EvoSize` tinyint(2) unsigned NOT NULL default '0',
	`Race` tinyint(2) unsigned NOT NULL default '0',
	`Element` tinyint(2) unsigned NOT NULL default '0',
	`bASPD` smallint(5) unsigned NOT NULL default '0',
	`bHP` smallint(5) unsigned NOT NULL default '0',
	`bSP` smallint(5) unsigned NOT NULL default '0',
	`bSTR` smallint(5) unsigned NOT NULL default '0',
	`bAGI` smallint(5) unsigned NOT NULL default '0',
	`bVIT` smallint(5) unsigned NOT NULL default '0',
	`bINT` smallint(5) unsigned NOT NULL default '0',
	`bDEX` smallint(5) unsigned NOT NULL default '0',
	`bLUK` smallint(5) unsigned NOT NULL default '0',
	`gnHP` smallint(5) unsigned NOT NULL default '0',
	`gxHP` smallint(5) unsigned NOT NULL default '0',
	`gnSP` smallint(5) unsigned NOT NULL default '0',
	`gxSP` smallint(5) unsigned NOT NULL default '0',
	`gnSTR` smallint(5) unsigned NOT NULL default '0',
	`gxSTR` smallint(5) unsigned NOT NULL default '0',
	`gnAGI` smallint(5) unsigned NOT NULL default '0',
	`gxAGI` smallint(5) unsigned NOT NULL default '0',
	`gnVIT` smallint(5) unsigned NOT NULL default '0',
	`gxVIT` smallint(5) unsigned NOT NULL default '0',
	`gnINT` smallint(5) unsigned NOT NULL default '0',
	`gxINT` smallint(5) unsigned NOT NULL default '0',
	`gnDEX` smallint(5) unsigned NOT NULL default '0',
	`gxDEX` smallint(5) unsigned NOT NULL default '0',
	`gnLUK` smallint(5) unsigned NOT NULL default '0',
	`gxLUK` smallint(5) unsigned NOT NULL default '0',
	`enHP` smallint(5) unsigned NOT NULL default '0',
	`exHP` smallint(5) unsigned NOT NULL default '0',
	`enSP` smallint(5) unsigned NOT NULL default '0',
	`exSP` smallint(5) unsigned NOT NULL default '0',
	`enSTR` smallint(5) unsigned NOT NULL default '0',
	`exSTR` smallint(5) unsigned NOT NULL default '0',
	`enAGI` smallint(5) unsigned NOT NULL default '0',
	`exAGI` smallint(5) unsigned NOT NULL default '0',
	`enVIT` smallint(5) unsigned NOT NULL default '0',
	`exVIT` smallint(5) unsigned NOT NULL default '0',
	`enINT` smallint(5) unsigned NOT NULL default '0',
	`exINT` smallint(5) unsigned NOT NULL default '0',
	`enDEX` smallint(5) unsigned NOT NULL default '0',
	`exDEX` smallint(5) unsigned NOT NULL default '0',
	`enLUK` smallint(5) unsigned NOT NULL default '0',
	`exLUK` smallint(5) unsigned NOT NULL default '0',
	PRIMARY KEY (`Class`)
) ENGINE=MyISAM;